// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN_EcZLyUqA4CEknTIf-snEir1RGZQmr8',
    appId: '1:23501020060:web:8947fe5db4cca26e000659',
    messagingSenderId: '23501020060',
    projectId: 'flutter-weekend-bb11b',
    authDomain: 'flutter-weekend-bb11b.firebaseapp.com',
    storageBucket: 'flutter-weekend-bb11b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHXDBPV8RKEGNHBRnQfozYnd1r2cQGI9E',
    appId: '1:23501020060:android:a8d11bfa245ec9a8000659',
    messagingSenderId: '23501020060',
    projectId: 'flutter-weekend-bb11b',
    storageBucket: 'flutter-weekend-bb11b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXQuBK1giCzg6DfooS_BH91DrIepobwMI',
    appId: '1:23501020060:ios:d58900f8f5afbd30000659',
    messagingSenderId: '23501020060',
    projectId: 'flutter-weekend-bb11b',
    storageBucket: 'flutter-weekend-bb11b.appspot.com',
    iosClientId: '23501020060-an119jjgcrbscqdrr560bdaeskgrta3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeekend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXQuBK1giCzg6DfooS_BH91DrIepobwMI',
    appId: '1:23501020060:ios:d58900f8f5afbd30000659',
    messagingSenderId: '23501020060',
    projectId: 'flutter-weekend-bb11b',
    storageBucket: 'flutter-weekend-bb11b.appspot.com',
    iosClientId: '23501020060-an119jjgcrbscqdrr560bdaeskgrta3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeekend',
  );
}
